# coding: utf-8

"""
    Pokedex API

    API for håndtering af Pokémon data ved brug af en Pandas DataFrame.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_add_data(self) -> None:
        """Test case for add_data

        Tilføj en ny Pokémon
        """
        pass

    def test_add_multiple_data(self) -> None:
        """Test case for add_multiple_data

        Tilføj flere Pokémon
        """
        pass

    def test_get_data(self) -> None:
        """Test case for get_data

        Hent alle Pokémon data
        """
        pass

    def test_get_filtered_data(self) -> None:
        """Test case for get_filtered_data

        Hent filtreret Pokémon data
        """
        pass

    def test_get_sorted_data(self) -> None:
        """Test case for get_sorted_data

        Hent sorteret Pokémon data
        """
        pass


if __name__ == '__main__':
    unittest.main()
