# coding: utf-8

"""
    Pokedex API

    API for håndtering af Pokémon data ved brug af en Pandas DataFrame.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.add_multiple_data200_response import AddMultipleData200Response

class TestAddMultipleData200Response(unittest.TestCase):
    """AddMultipleData200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddMultipleData200Response:
        """Test AddMultipleData200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddMultipleData200Response`
        """
        model = AddMultipleData200Response()
        if include_optional:
            return AddMultipleData200Response(
                message = 'Entries added successfully'
            )
        else:
            return AddMultipleData200Response(
        )
        """

    def testAddMultipleData200Response(self):
        """Test AddMultipleData200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
